import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import db from "./database.js";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Absolute path to the directory containing migration SQL files.
const MIGRATIONS_DIR = path.join(__dirname, "migrations");

// Executes a SQL statement using sqlite3's db.run and returns a Promise.
// This converts the callback-based sqlite API into a Promise-based one,
// allowing callers to use async/await in migrations or other DB code.
//
// Parameters:
//   sql    - SQL statement to execute (INSERT, UPDATE, DELETE, schema change, etc.)
//   params - optional array of values bound to SQL placeholders (?)
//
// Resolves with:
//   { changes, lastID }
//     changes → number of rows affected by the statement
//     lastID  → row ID generated by the most recent INSERT
//
// Rejects with the sqlite error if execution fails.
function run(sql, params = []) {
  return new Promise((resolve, reject) => {
    // Execute the SQL statement with bound parameters
    db.run(sql, params, function (err) {
      // If sqlite returns an error, reject the Promise
      if (err) return reject(err);

      // Use a normal function instead of an arrow function so that
      // `this` refers to the sqlite Statement context provided by
      // the driver, which exposes `changes` and `lastID`.
      resolve({ changes: this.changes, lastID: this.lastID });
    });
  });
}

// Executes a SQL query using sqlite3's db.all and returns a Promise.
// This wraps the callback-based sqlite API so callers can use async/await.
//
// Parameters:
//   sql    - SQL SELECT query to execute
//   params - optional array of values bound to SQL placeholders (?)
//
// Resolves with:
//   rows → an array of result objects returned by the query
//
// Rejects with the sqlite error if the query fails.
function all(sql, params = []) {
  return new Promise((resolve, reject) => {
    // Execute the query and retrieve all matching rows
    db.all(sql, params, (err, rows) => {
      // Reject the Promise if sqlite reports an error
      if (err) return reject(err);

      // Resolve with the full result set
      resolve(rows);
    });
  });
}

export async function runMigrations() {
  await run(`
    CREATE TABLE IF NOT EXISTS migrations (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      filename TEXT NOT NULL UNIQUE,
      applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
    )
  `);

  /**
   * Read all files in the migrations directory.
   *
   * Steps:
   * 1. Read directory contents
   * 2. Keep only .sql files
   * 3. Sort alphabetically to ensure deterministic order
   */
  const files = (await fs.readdir(MIGRATIONS_DIR))
    .filter((f) => f.endsWith(".sql"))
    .sort();

  /**
   * Query database to determine which migrations
   * have already been applied.
   */
  const appliedRows = await all(`SELECT filename FROM migrations`);

  /**
   * Convert filenames into a Set for fast lookup.
   *
   * Concept: Sets provide O(1) lookup time and enforce uniqueness.
   */
  const appliedMigrations = new Set(appliedRows.map((r) => r.filename));

  // Itereate through all migration files
  for (const filename of files) {
    // Skip any migration that already applied
    if (appliedMigrations.has(filename)) continue;

    // Build an asolute path to the migration file
    const fullPath = path.join(MIGRATIONS_DIR, filename);

    // Load the SQL content from the migration files
    const sql = await fs.readFile(fullPath, "utf8");

    /**
     * Database Transaction
     *
     * Either all operations succeed, or all operations fail.
     *
     * This prevents partially applied migrations that could
     * leave the schema in an inconsistent state.
     */
    await run("BEGIN");
    try {
      // Execute the migration file
      await run(sql);

      // Records the migration was successfully applied
      await run(`INSERT INTO migrations (filename) VALUES (?)`, [filename]);

      // Commits the transaction once successful
      await run("COMMIT");
    } catch (err) {
      // Rolls back changes if any step fails
      await run("ROLLBACK");
      throw err;
    }
  }
}
