import db from "../database.js";

/**
 * Fetches a list of leads with optional search, filtering, pagination, and sorting.
 *
 * Parameters:
 *   limit      → number of rows to return
 *   offset     → number of rows to skip
 *   search     → optional search string
 *
 * This function builds a dynamic SQL query depending on which filters exist.
 *
 * Instead of writing many different SQL queries, we assemble the WHERE clause
 * based on the filters provided by the API request.
 */
export function getAllLeads(limit, offset, search) {
  return new Promise((resolve, reject) => {
    // Holds SQL conditionals (LIKE, WHERE, etc)
    const conditions = [];

    /**
     * params stores values that replace SQL placeholders (?).
     *
     * Using placeholders prevents SQL injection and allows the
     * database driver to safely bind user input.
     */
    const params = [];

    /**
     * Optional search filter.
     *
     * %${search}% acts as a wildcard: %smith% matches "John Smith", etc.
     */
    if (search) {
      conditions.push(
        `(first_name LIKE ? OR last_name LIKE ? OR company LIKE ?)`,
      );

      const pattern = `%${search}%`;
      params.push(pattern, pattern, pattern);
    }

    /**
     * Constructs the WHERE clause dynamically.
     *
     * If conditions exist:
     *   WHERE condition1 AND condition2
     *
     * If no conditions exist:
     *   (empty string → no WHERE clause)
     */
    const whereClause =
      conditions.length > 0 ? `WHERE ${conditions.join(" AND ")}` : "";

    /**
     * Main query used to fetch paginated rows.
     *
     * ORDER BY created_date DESC ensures newest leads appear first.
     *
     * LIMIT and OFFSET implement pagination.
     */
    const dataSql = `
      SELECT
        id,
        first_name,
        last_name,
        email,
        phone,
        company,
        status,
        created_on,
        updated_on
        FROM leads
      ${whereClause}
      ORDER BY created_on DESC
      LIMIT ? OFFSET ?
    `;

    /**
     * Separate query used to count total matching rows.
     *
     * Pagination APIs often return both:
     *   - the current page of results
     *   - the total number of records
     *
     * This allows clients (frontends) to render page numbers
     * or calculate how many pages exist.
     */
    const countSql = `
      SELECT COUNT(*) as total
      FROM leads
      ${whereClause}
    `;

    // Executes the count query to return a single row instead of the array
    db.get(countSql, params, (countErr, countRow) => {
      if (countErr) return reject(countErr);

      const total = countRow.total;

      /**
       * Executes the main data query.
       *
       */
      db.all(dataSql, [...params, limit, offset], (dataErr, rows) => {
        if (dataErr) return reject(dataErr);

        /**
         * The Promise resolves with both:
         * - rows  → actual data
         * - total → number of matching rows
         */
        resolve({
          rows,
          total,
        });
      });
    });
  });
}

/**
 * Fetches a single lead by ID.
 *
 * Returns:
 *   - the lead object if found
 *   - undefined if no lead exists with that ID
 */
export function getLeadById(id) {
  return new Promise((resolve, reject) => {
    /**
     * ? is a parameter placeholder.
     *
     * This prevents SQL injection because sqlite3
     * safely escapes the value.
     */
    const sql = `
      SELECT
        id,
        first_name,
        last_name,
        email,
        phone,
        company,
        status,
        created_on,
        updated_on
      FROM leads
      WHERE id = ?
    `;

    // db.get returns a SINGLE row
    db.get(sql, [id], (err, row) => {
      if (err) return reject(err);

      resolve(row);
    });
  });
}

/**
 * Creates a new lead.
 *
 * This inserts a new record into the leads table.
 */
export function createLead({
  first_name,
  last_name,
  email,
  phone,
  company,
  status,
}) {
  return new Promise((resolve, reject) => {
    const sql = `
      INSERT INTO leads (
        first_name,
        last_name,
        email,
        phone,
        company,
        status)
      VALUES (?, ?, ?, ?, ?, ?)
  `;

    // params replaces the ? in the VALUES in the sql variable
    const params = [first_name, last_name, email, phone, company, status];

    // db.run will execute the sql statement based off of params
    db.run(sql, params, function (err) {
      if (err) return reject(err);

      /**
       * sqlite3 attaches metadata to the statement context.
       *
       * lastID = primary key generated by the INSERT.
       */
      resolve({
        id: this.lastID,
      });
    });
  });
}

/**
 * Deletes a lead by ID.
 */
export function deleteLead(id) {
  return new Promise((resolve, reject) => {
    const sql = `DELETE FROM leads WHERE id = ?`;

    db.run(sql, [id], function (err) {
      if (err) return reject(err);

      /**
       * changes indicates how many rows were affected.
       *
       * If changes === 0:
       *   no lead existed with that ID.
       */
      resolve({
        changes: this.changes,
      });
    });
  });
}

/**
 * Updates an existing lead by ID.
 *
 * All fields are replaced with the provided values.
 */
export function updateLeadById(
  id,
  { first_name, last_name, email, phone, company, status },
) {
  return new Promise((resolve, reject) => {
    const sql = `
      UPDATE leads
      SET
        first_name = ?,
        last_name = ?,
        email = ?,
        phone = ?,
        company = ?,
        status = ?,
        updated_on = CURRENT_TIMESTAMP
      WHERE id = ?
    `;

    /**
     * Values must appear in the same order as the
     * placeholders in the SQL statement.
     */
    const params = [first_name, last_name, email, phone, company, status, id];

    db.run(sql, params, function (err) {
      if (err) return reject(err);

      /**
       * changes indicates whether a row was updated.
       *
       * If 0 → no matching task ID existed.
       */
      resolve({
        changes: this.changes,
      });
    });
  });
}
