INSERT INTO leads
(first_name, last_name, email, phone, company, status, created_on)
VALUES
('James','Anderson','j.anderson@andersontech.com','+1-555-3101','Anderson Technologies','New',datetime('now','-100 days')),
('Olivia','Martinez','olivia.martinez@martinezgroup.com','+1-555-3102','Martinez Group','Contacted',datetime('now','-99 days')),
('Liam','Thompson','liam.thompson@thompsonsolutions.com','+1-555-3103','Thompson Solutions','Qualified',datetime('now','-98 days')),
('Emma','Garcia','emma.garcia@garciaconsulting.com','+1-555-3104','Garcia Consulting','Proposal',datetime('now','-97 days')),
('Noah','Robinson','noah.robinson@robinsonindustries.com','+1-555-3105','Robinson Industries','Negotiation',datetime('now','-96 days')),
('Ava','Clark','ava.clark@clarkenterprises.com','+1-555-3106','Clark Enterprises','Won',datetime('now','-95 days')),
('Elijah','Lewis','elijah.lewis@lewissystems.com','+1-555-3107','Lewis Systems','Lost',datetime('now','-94 days')),
('Sophia','Walker','sophia.walker@walkerlogistics.com','+1-555-3108','Walker Logistics','New',datetime('now','-93 days')),
('William','Hall','william.hall@hallpartners.com','+1-555-3109','Hall Partners','Contacted',datetime('now','-92 days')),
('Isabella','Allen','isabella.allen@allenventures.com','+1-555-3110','Allen Ventures','Qualified',datetime('now','-91 days')),

('Lucas','Young','lucas.young@younggroup.com','+1-555-3111','Young Group','Proposal',datetime('now','-90 days')),
('Mia','Hernandez','mia.hernandez@hernandeztech.com','+1-555-3112','Hernandez Tech','Negotiation',datetime('now','-89 days')),
('Henry','King','henry.king@kingindustries.com','+1-555-3113','King Industries','Won',datetime('now','-88 days')),
('Charlotte','Wright','charlotte.wright@wrightsolutions.com','+1-555-3114','Wright Solutions','Lost',datetime('now','-87 days')),
('Alexander','Lopez','alex.lopez@lopezconsulting.com','+1-555-3115','Lopez Consulting','New',datetime('now','-86 days')),
('Amelia','Hill','amelia.hill@hillenterprises.com','+1-555-3116','Hill Enterprises','Contacted',datetime('now','-85 days')),
('Michael','Scott','michael.scott@scottlogistics.com','+1-555-3117','Scott Logistics','Qualified',datetime('now','-84 days')),
('Harper','Green','harper.green@greenpartners.com','+1-555-3118','Green Partners','Proposal',datetime('now','-83 days')),
('Daniel','Adams','daniel.adams@adamsventures.com','+1-555-3119','Adams Ventures','Negotiation',datetime('now','-82 days')),
('Evelyn','Baker','evelyn.baker@bakertech.com','+1-555-3120','Baker Tech','Won',datetime('now','-81 days')),

('Matthew','Nelson','matthew.nelson@nelsongroup.com','+1-555-3121','Nelson Group','Lost',datetime('now','-80 days')),
('Abigail','Carter','abigail.carter@cartersolutions.com','+1-555-3122','Carter Solutions','New',datetime('now','-79 days')),
('Joseph','Mitchell','joseph.mitchell@mitchellconsulting.com','+1-555-3123','Mitchell Consulting','Contacted',datetime('now','-78 days')),
('Emily','Perez','emily.perez@perezindustries.com','+1-555-3124','Perez Industries','Qualified',datetime('now','-77 days')),
('David','Roberts','david.roberts@robertsenterprises.com','+1-555-3125','Roberts Enterprises','Proposal',datetime('now','-76 days')),
('Elizabeth','Turner','elizabeth.turner@turnertech.com','+1-555-3126','Turner Tech','Negotiation',datetime('now','-75 days')),
('Samuel','Phillips','samuel.phillips@phillipsgroup.com','+1-555-3127','Phillips Group','Won',datetime('now','-74 days')),
('Sofia','Campbell','sofia.campbell@campbelllogistics.com','+1-555-3128','Campbell Logistics','Lost',datetime('now','-73 days')),
('Jackson','Parker','jackson.parker@parkerpartners.com','+1-555-3129','Parker Partners','New',datetime('now','-72 days')),
('Avery','Evans','avery.evans@evansventures.com','+1-555-3130','Evans Ventures','Contacted',datetime('now','-71 days')),

('Sebastian','Edwards','sebastian.edwards@edwardstech.com','+1-555-3131','Edwards Tech','Qualified',datetime('now','-70 days')),
('Ella','Collins','ella.collins@collinssolutions.com','+1-555-3132','Collins Solutions','Proposal',datetime('now','-69 days')),
('Aiden','Stewart','aiden.stewart@stewartindustries.com','+1-555-3133','Stewart Industries','Negotiation',datetime('now','-68 days')),
('Scarlett','Sanchez','scarlett.sanchez@sanchezconsulting.com','+1-555-3134','Sanchez Consulting','Won',datetime('now','-67 days')),
('Logan','Morris','logan.morris@morrisenterprises.com','+1-555-3135','Morris Enterprises','Lost',datetime('now','-66 days')),
('Grace','Rogers','grace.rogers@rogerstech.com','+1-555-3136','Rogers Tech','New',datetime('now','-65 days')),
('Owen','Reed','owen.reed@reedgroup.com','+1-555-3137','Reed Group','Contacted',datetime('now','-64 days')),
('Chloe','Cook','chloe.cook@cooklogistics.com','+1-555-3138','Cook Logistics','Qualified',datetime('now','-63 days')),
('Gabriel','Morgan','gabriel.morgan@morganpartners.com','+1-555-3139','Morgan Partners','Proposal',datetime('now','-62 days')),
('Victoria','Bell','victoria.bell@bellventures.com','+1-555-3140','Bell Ventures','Negotiation',datetime('now','-61 days')),

('Carter','Murphy','carter.murphy@murphytech.com','+1-555-3141','Murphy Tech','Won',datetime('now','-60 days')),
('Riley','Bailey','riley.bailey@baileysolutions.com','+1-555-3142','Bailey Solutions','Lost',datetime('now','-59 days')),
('Jayden','Rivera','jayden.rivera@riveraindustries.com','+1-555-3143','Rivera Industries','New',datetime('now','-58 days')),
('Aria','Cooper','aria.cooper@cooperconsulting.com','+1-555-3144','Cooper Consulting','Contacted',datetime('now','-57 days')),
('Luke','Richardson','luke.richardson@richardsongroup.com','+1-555-3145','Richardson Group','Qualified',datetime('now','-56 days')),
('Lily','Cox','lily.cox@coxenterprises.com','+1-555-3146','Cox Enterprises','Proposal',datetime('now','-55 days')),
('Julian','Howard','julian.howard@howardtech.com','+1-555-3147','Howard Tech','Negotiation',datetime('now','-54 days')),
('Aubrey','Ward','aubrey.ward@wardpartners.com','+1-555-3148','Ward Partners','Won',datetime('now','-53 days')),
('Levi','Torres','levi.torres@torressolutions.com','+1-555-3149','Torres Solutions','Lost',datetime('now','-52 days')),
('Zoey','Peterson','zoey.peterson@petersonindustries.com','+1-555-3150','Peterson Industries','New',datetime('now','-51 days')),

('Caleb','Gray','caleb.gray@graygroup.com','+1-555-3151','Gray Group','Contacted',datetime('now','-50 days')),
('Hannah','Ramirez','hannah.ramirez@ramireztech.com','+1-555-3152','Ramirez Tech','Qualified',datetime('now','-49 days')),
('Nathan','James','nathan.james@jamesconsulting.com','+1-555-3153','James Consulting','Proposal',datetime('now','-48 days')),
('Zoe','Watson','zoe.watson@watsonenterprises.com','+1-555-3154','Watson Enterprises','Negotiation',datetime('now','-47 days')),
('Isaac','Brooks','isaac.brooks@brooksgroup.com','+1-555-3155','Brooks Group','Won',datetime('now','-46 days')),
('Addison','Kelly','addison.kelly@kellytech.com','+1-555-3156','Kelly Tech','Lost',datetime('now','-45 days')),
('Anthony','Sanders','anthony.sanders@sanderssolutions.com','+1-555-3157','Sanders Solutions','New',datetime('now','-44 days')),
('Layla','Price','layla.price@priceindustries.com','+1-555-3158','Price Industries','Contacted',datetime('now','-43 days')),
('Andrew','Bennett','andrew.bennett@bennettconsulting.com','+1-555-3159','Bennett Consulting','Qualified',datetime('now','-42 days')),
('Nora','Wood','nora.wood@woodgroup.com','+1-555-3160','Wood Group','Proposal',datetime('now','-41 days')),

('Christopher','Barnes','christopher.barnes@barnestech.com','+1-555-3161','Barnes Tech','Negotiation',datetime('now','-40 days')),
('Lillian','Ross','lillian.ross@rossventures.com','+1-555-3162','Ross Ventures','Won',datetime('now','-39 days')),
('Joshua','Henderson','joshua.henderson@hendersonpartners.com','+1-555-3163','Henderson Partners','Lost',datetime('now','-38 days')),
('Natalie','Coleman','natalie.coleman@colemangroup.com','+1-555-3164','Coleman Group','New',datetime('now','-37 days')),
('Aaron','Jenkins','aaron.jenkins@jenkinstech.com','+1-555-3165','Jenkins Tech','Contacted',datetime('now','-36 days')),
('Brooklyn','Perry','brooklyn.perry@perrysolutions.com','+1-555-3166','Perry Solutions','Qualified',datetime('now','-35 days')),
('Christian','Powell','christian.powell@powellindustries.com','+1-555-3167','Powell Industries','Proposal',datetime('now','-34 days')),
('Samantha','Long','samantha.long@longconsulting.com','+1-555-3168','Long Consulting','Negotiation',datetime('now','-33 days')),
('Jonathan','Patterson','jonathan.patterson@pattersonenterprises.com','+1-555-3169','Patterson Enterprises','Won',datetime('now','-32 days')),
('Penelope','Hughes','penelope.hughes@hughesgroup.com','+1-555-3170','Hughes Group','Lost',datetime('now','-31 days')),

('Isaiah','Flores','isaiah.flores@florestech.com','+1-555-3171','Flores Tech','New',datetime('now','-30 days')),
('Violet','Washington','violet.washington@washingtonsolutions.com','+1-555-3172','Washington Solutions','Contacted',datetime('now','-29 days')),
('Charles','Butler','charles.butler@butlerindustries.com','+1-555-3173','Butler Industries','Qualified',datetime('now','-28 days')),
('Aurora','Simmons','aurora.simmons@simmonsconsulting.com','+1-555-3174','Simmons Consulting','Proposal',datetime('now','-27 days')),
('Thomas','Foster','thomas.foster@fostergroup.com','+1-555-3175','Foster Group','Negotiation',datetime('now','-26 days')),
('Savannah','Gonzales','savannah.gonzales@gonzalestech.com','+1-555-3176','Gonzales Tech','Won',datetime('now','-25 days')),
('Eli','Bryant','eli.bryant@bryantventures.com','+1-555-3177','Bryant Ventures','Lost',datetime('now','-24 days')),
('Claire','Alexander','claire.alexander@alexandersolutions.com','+1-555-3178','Alexander Solutions','New',datetime('now','-23 days')),
('Ryan','Russell','ryan.russell@russellindustries.com','+1-555-3179','Russell Industries','Contacted',datetime('now','-22 days')),
('Skylar','Griffin','skylar.griffin@griffinconsulting.com','+1-555-3180','Griffin Consulting','Qualified',datetime('now','-21 days')),

('Adrian','Diaz','adrian.diaz@diazgroup.com','+1-555-3181','Diaz Group','Proposal',datetime('now','-20 days')),
('Lucy','Hayes','lucy.hayes@hayestech.com','+1-555-3182','Hayes Tech','Negotiation',datetime('now','-19 days')),
('Ethan','Myers','ethan.myers@myerspartners.com','+1-555-3183','Myers Partners','Won',datetime('now','-18 days')),
('Paisley','Ford','paisley.ford@fordindustries.com','+1-555-3184','Ford Industries','Lost',datetime('now','-17 days')),
('Hudson','Hamilton','hudson.hamilton@hamiltonconsulting.com','+1-555-3185','Hamilton Consulting','New',datetime('now','-16 days')),
('Everly','Graham','everly.graham@grahamgroup.com','+1-555-3186','Graham Group','Contacted',datetime('now','-15 days')),
('Connor','Sullivan','connor.sullivan@sullivantech.com','+1-555-3187','Sullivan Tech','Qualified',datetime('now','-14 days')),
('Kennedy','Wallace','kennedy.wallace@wallaceventures.com','+1-555-3188','Wallace Ventures','Proposal',datetime('now','-13 days')),
('Jaxon','Woods','jaxon.woods@woodssolutions.com','+1-555-3189','Woods Solutions','Negotiation',datetime('now','-12 days')),
('Naomi','Cole','naomi.cole@coleindustries.com','+1-555-3190','Cole Industries','Won',datetime('now','-11 days')),

('Hunter','West','hunter.west@westgroup.com','+1-555-3191','West Group','Lost',datetime('now','-10 days')),
('Elena','Jordan','elena.jordan@jordantech.com','+1-555-3192','Jordan Tech','New',datetime('now','-9 days')),
('Dominic','Owens','dominic.owens@owenspartners.com','+1-555-3193','Owens Partners','Contacted',datetime('now','-8 days')),
('Maya','Reynolds','maya.reynolds@reynoldsindustries.com','+1-555-3194','Reynolds Industries','Qualified',datetime('now','-7 days')),
('Adam','Fisher','adam.fisher@fisherconsulting.com','+1-555-3195','Fisher Consulting','Proposal',datetime('now','-6 days')),
('Aaliyah','Ellis','aaliyah.ellis@ellisgroup.com','+1-555-3196','Ellis Group','Negotiation',datetime('now','-5 days')),
('Ian','Harrison','ian.harrison@harrisontech.com','+1-555-3197','Harrison Tech','Won',datetime('now','-4 days')),
('Madelyn','Gibson','madelyn.gibson@gibsonventures.com','+1-555-3198','Gibson Ventures','Lost',datetime('now','-3 days')),
('Carson','McDonald','carson.mcdonald@mcdonaldsolutions.com','+1-555-3199','McDonald Solutions','New',datetime('now','-2 days')),
('Serenity','Cruz','serenity.cruz@cruzindustries.com','+1-555-3200','Cruz Industries','Contacted',datetime('now','-1 day'));